### ISSUE TITLE
Method named "getNickname" does not exist

### ISSUE THREAD

**Issue by topikito** [bramdevries/oauth2-slack#2]
Hi!

On the example on the Readme:

```
        // We got an access token, let's now get the user's details
        $user = $provider->getResourceOwner($token);

        // Use these details to create a new profile
        printf('Hello %s!', $user->getNickname());
```

you use a method "getNickname" that does not exist in the interface `ResourceOwnerInterface` (which is the type thats being returned).

**Comment by iNilo** [comment]
Bump :(

**Comment by bramdevries** [comment]
Sorry, I'm not actually maintaining this package anymore. It has not been updated in over 5 years and I actually forgot that it existed. I suggest you either use https://github.com/adam-paterson/oauth2-slack or write your own implementation
