### ISSUE TITLE
Provider class name in readme/docs differs from actual

### ISSUE THREAD

**Issue by ChaoticWeg** [bramdevries/oauth2-slack#3]
Class `Bramdevries\Oauth\Client\Provider\Slack` differs from the docs, where `League\OAuth2\Client\Provider\Slack` is used. I couldn't get the latter to work at all, until it was pointed out to me that the former should be used (and works).

**Comment by SimonPrague** [comment]
I had the same problem. I fixed it by using:
```php
use Bramdevries\Oauth\Client\Provider\Slack;
// ...
$provider = new Bramdevries\Oauth\Client\Provider\Slack([
// ...
```
